name: "env variable"

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'commit SHA'
        required: false

environment:
  sha: ${{ github.event.inputs.sha || github.sha }}
        
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Echoing
        run: echo " lala ${{ env.sha }}"
